load("@rules_cc//cc:cc_binary.bzl", "cc_binary")
load("@rules_cc//cc:cc_library.bzl", "cc_library")

# @unused
load("@rules_cc//cc:cc_test.bzl", "cc_test")

cc_library(
    name = "cpu",
    srcs = ["src/cpu/cpu.c"],
    hdrs = ["src/cpu/cpu.h"],
    includes = ["src"],
)

cc_library(
    name = "ppu",
    srcs = ["src/ppu/ppu.c"],
    hdrs = ["src/ppu/ppu.h"],
    includes = ["src"],
)

cc_library(
    name = "rom",
    srcs = ["src/rom/rom.c"],
    hdrs = ["src/rom/rom.h"],
    includes = ["src"],
)

cc_library(
    name = "cartridge",
    srcs = ["src/cartridge/cartridge.c"],
    hdrs = ["src/cartridge/cartridge.h"],
    includes = ["src"],
    deps = [
        ":cpu",
        ":ppu",
        ":rom",
    ],
)

cc_library(
    name = "machine",
    srcs = ["src/machine/machine.c"],
    hdrs = ["src/machine/machine.h"],
    includes = ["src"],
    deps = [
        ":cartridge",
        ":cpu",
        ":ppu",
    ],
)

cc_library(
    name = "sdl",
    srcs = ["src/sdl/sdl.c"],
    hdrs = ["src/sdl/sdl.h"],
    includes = ["src"],
    deps = [":machine"],
)

cc_binary(
    name = "tnes-debug",
    srcs = ["src/main_debug.c"],
    deps = [
        ":cartridge",
        ":cpu",
        ":machine",
        ":ppu",
        ":rom",
    ],
)

cc_binary(
    name = "tnes",
    srcs = ["src/main_sdl.c"],
    linkopts = [
        "-lSDL3",
        "-lSDL3_ttf",
    ],
    deps = [
        ":cartridge",
        ":cpu",
        ":machine",
        ":ppu",
        ":rom",
        ":sdl",
    ],
)

# cc_test(
#     name = "cpu_test",
#     srcs = ["tests/cpu_test.c"],
#     deps = [":cpu"],
# )

# cc_test(
#     name = "bus_test",
#     srcs = ["tests/bus_test.c"],
#     deps = [":bus"],
# )

# cc_test(
#     name = "ppu_test",
#     srcs = ["tests/ppu_test.c"],
#     deps = [":ppu"],
# )
